# This is a basic workflow to help you get started with Actions

name: Staged Deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "feat/staged-deploy" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      module-stage:
        type: choice
        description: Which module stage to deploy
        options:
        - 0-all
        - 1-bootstrap
        - 2-network
        - 3-security
        - 4-project

env:
  TF_INPUT: false
  TF_IN_AUTOMATION: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prepare:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MODULESTAGE: ${{ github.event.inputs.module-stage }}
    outputs:
      environment: ${{ steps.determine-env.outputs.environment }}
      applystages: ${{ steps.determine-stages.outputs.applystages }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: determine env
        id: determine-env
        run: |
          echo "environment=prod" >> $GITHUB_OUTPUT
      - name: determine stages
        id: determine-stages
        run: |
          echo "Stage: ${{ github.event.inputs.module-stage }}"
          [ -z "$MODULESTAGE" ] || [[ $MODULESTAGE == 0-* ]] && echo 'applystages=[ "1-bootstrap", "2-network", "3-security", "4-project"]' >> $GITHUB_OUTPUT || echo "applystages=$MODULESTAGE" >> $GITHUB_OUTPUT
          echo "stages=1-bootstrap,2-network,3-security,4-project" >> $GITHUB_OUTPUT

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix:
        stages: [ '1-bootstrap' ]
      max-parallel: 1 # important to ensure sequential execution
    environment: ${{ needs.prepare.outputs.environment }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: terraform-linters/setup-tflint@v3
        with:
          tflint_version: v0.48.0
      - name: Terraform init
        id: tf-init
        run: |
          terraform -chdir=${{ matrix.stages }} init
      - name: Terraform plan
        id: tf-plan
        run: |
          terraform -chdir=${{ matrix.stages }} plan
  
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: ${{ needs.prepare.outputs.applystages != '' }}
    needs: [plan]
    # strategy:
    #   matrix:
    #     stages: ${{ fromJson(needs.prepare.outputs.applystages) }}
    #   max-parallel: 1 # important to ensure sequential execution
    environment: ${{ needs.prepare.outputs.environment }}
    steps:
      - name: Terraform apply
        id: tf-apply
        run: |
          echo "Apply stages: ${{ needs.prepare.outputs.applystages }}"
